CREATE TYPE "estado_caso" AS ENUM (
  'abierto',
  'cerrado'
);

CREATE TYPE "estado_incidente" AS ENUM (
  'aceptado',
  'pendiente',
  'rechazado'
);

CREATE TYPE "gravedad" AS ENUM (
  'leve',
  'grave',
  'muy_grave'
);

CREATE TYPE "tipo_hito" AS ENUM (
  'tramite',
  'medida'
);

CREATE TYPE "nivel_medida" AS ENUM (
  'cautelar',
  'formativa_n1',
  'disciplinaria_n2',
  'excepcional_n3'
);

CREATE TYPE "rol_involucrado" AS ENUM (
  'afectado_victima',
  'autor_agresor',
  'complice',
  'testigo_espectador'
);

CREATE TYPE "categoria_convivencia" AS ENUM (
  'violencia_fisica',
  'violencia_psicologica_acoso',
  'disrupcion_desacato',
  'probidad_fraude',
  'dano_infraestructura_bienes',
  'conductas_riesgo_sustancias',
  'privacidad_tecnologia',
  'sexualidad_obscenidad',
  'valores_institucionales',
  'otro'
);

CREATE TYPE "categoria_tramite" AS ENUM (
  'comunicacion_citaciones',
  'derivaciones',
  'documentacion',
  'coordinacion_interna'
);

CREATE TYPE "subtipo_tramite" AS ENUM (
  -- Comunicación y citaciones
  'citacion_apoderado',
  'entrevista_estudiante',
  'entrevista_apoderado',
  'notificacion_formal',
  
  -- Derivaciones
  'derivacion_orientacion',
  'derivacion_psicologo',
  'derivacion_dupla_psicosocial',
  'derivacion_red_externa',
  
  -- Documentación
  'firma_compromiso',
  'acta_reunion',
  'registro_libro_clases',
  'informe_seguimiento',
  
  -- Coordinación interna
  'reunion_equipo_directivo',
  'comunicacion_inspector_general',
  'activacion_protocolo'
);


CREATE TABLE "Usuario" (
  "id_usuario" varchar PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "email" varchar NOT NULL, 
  "tipo_usuario" varchar NOT NULL,
  "es_activo" boolean DEFAULT true,
  "hashed_password" varchar NOT NULL,
  CHECK (tipo_usuario IN ('coordinador', 'productor', 'profesor_jefe'))
);
CREATE UNIQUE INDEX "unique_email_active_users" ON "Usuario" ("email") WHERE "es_activo" = true;

CREATE TABLE "Coordinador" (
  "id_usuario" varchar PRIMARY KEY
);

CREATE TABLE "Productor" (
  "id_usuario" varchar PRIMARY KEY
);

CREATE TABLE "ProfesorJefe" (
  "id_usuario" varchar PRIMARY KEY
);

CREATE TABLE "Estudiante" (
  "id_estudiante" varchar PRIMARY KEY, 
  "nombre" varchar NOT NULL,
  "id_curso" integer
);

CREATE TABLE "Curso" (
  "id_curso" integer PRIMARY KEY,
  "nombre_curso" varchar NOT NULL,
  "id_pj" varchar UNIQUE NOT NULL 
);

CREATE TABLE "Caso" (
  "id_caso" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_coordinador" varchar NOT NULL,
  "estado" estado_caso NOT NULL,
  "fecha_inicio" date NOT NULL,
  "fecha_cierre" date,
  "desc" text NOT NULL,
  "gravedad" gravedad NOT NULL,
  "categoria" categoria_convivencia NOT NULL,
  "es_activo" boolean DEFAULT true,
);

CREATE TABLE "Hito" (
  "id_hito" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_caso" integer NOT NULL,
  "tipo" tipo_hito NOT NULL,
  
  "nivel_medida" nivel_medida,
  "categoria_tramite" categoria_tramite,
  "subtipo_tramite" subtipo_tramite,
  
  "desc" text NOT NULL,
  "fecha" date NOT NULL,
  "es_activo" boolean DEFAULT true,
  
  -- Exclusividad mutua entre Medida y Trámite
  CONSTRAINT "chk_hito_tipo_exclusivo" 
  CHECK (
    (tipo = 'medida'::tipo_hito AND nivel_medida IS NOT NULL AND categoria_tramite IS NULL AND subtipo_tramite IS NULL) OR 
    (tipo = 'tramite'::tipo_hito AND nivel_medida IS NULL AND categoria_tramite IS NOT NULL AND subtipo_tramite IS NOT NULL)
  ),
  
  -- Jerarquía estricta de Trámites
  CONSTRAINT "chk_jerarquia_tramite"
  CHECK (
    (categoria_tramite = 'comunicacion_citaciones'::categoria_tramite AND subtipo_tramite IN ('citacion_apoderado', 'entrevista_estudiante', 'entrevista_apoderado', 'notificacion_formal')) OR
    (categoria_tramite = 'derivaciones'::categoria_tramite AND subtipo_tramite IN ('derivacion_orientacion', 'derivacion_psicologo', 'derivacion_dupla_psicosocial', 'derivacion_red_externa')) OR
    (categoria_tramite = 'documentacion'::categoria_tramite AND subtipo_tramite IN ('firma_compromiso', 'acta_reunion', 'registro_libro_clases', 'informe_seguimiento')) OR
    (categoria_tramite = 'coordinacion_interna'::categoria_tramite AND subtipo_tramite IN ('reunion_equipo_directivo', 'comunicacion_inspector_general', 'activacion_protocolo')) OR
    (categoria_tramite IS NULL AND subtipo_tramite IS NULL)
  )
);

CREATE TABLE "Incidente" (
  "id_incidente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_productor" varchar NOT NULL,
  "gravedad" gravedad NOT NULL,
  "desc" text NOT NULL,
  "fecha" date NOT NULL,
  "id_caso" integer,
  "estado" estado_incidente NOT NULL,
  "motivo_rechazo" text,
  "categoria" categoria_convivencia NOT NULL,
  "es_activo" boolean DEFAULT true,

  CONSTRAINT "estado_incidente_1"
  CHECK (estado = 'aceptado'::estado_incidente OR id_caso is NULL),
  CONSTRAINT "estado_incidente_2"
  CHECK (estado != 'aceptado'::estado_incidente OR id_caso is not NULL),
  CONSTRAINT "motivo_rechazo_1"
  CHECK (estado = 'rechazado'::estado_incidente OR motivo_rechazo is NULL),
  CONSTRAINT "motivo_rechazo_2"
  CHECK (estado != 'rechazado'::estado_incidente OR motivo_rechazo is not NULL)
);

CREATE TABLE "Documento" (
  "id_doc" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bucket_name" varchar NOT NULL,
  "object_key" varchar UNIQUE NOT NULL,
  "nombre_original" varchar NOT NULL,
  "mime_type" varchar NOT NULL,
  "size_bytes" bigint NOT NULL,
  "descripcion" text NOT NULL,
  "id_hito" integer,
  "id_caso" integer,
  "id_incidente" integer

  CONSTRAINT chk_doc_pertenencia CHECK (
      num_nonnulls(id_hito, id_caso, id_incidente) = 1
  )
);

CREATE TABLE "Estudiante_Caso" (
  "id_estudiante" varchar NOT NULL,
  "id_caso" integer NOT NULL,
  "rol" rol_involucrado,
  PRIMARY KEY ("id_estudiante", "id_caso")
);

CREATE TABLE "Estudiante_Incidente" (
  "id_estudiante" varchar NOT NULL,
  "id_incidente" integer NOT NULL,
  "rol" rol_involucrado,
  PRIMARY KEY ("id_estudiante", "id_incidente")
);

CREATE TABLE "Estudiante_Hito" (
  "id_estudiante" varchar NOT NULL,
  "id_hito" integer NOT NULL,
  PRIMARY KEY ("id_estudiante", "id_hito")
);

COMMENT ON COLUMN "Documento"."bucket_name" IS 'Ej: ''evidencias'', ''documentos''';
COMMENT ON COLUMN "Documento"."object_key" IS 'El UUID o path en MinIO, ej: ''2026/05/uuid.pdf''';
COMMENT ON COLUMN "Documento"."nombre_original" IS 'Ej: ''informe_final.docx''';
COMMENT ON COLUMN "Documento"."mime_type" IS 'Ej: ''application/pdf''';

ALTER TABLE "Coordinador" ADD FOREIGN KEY ("id_usuario") REFERENCES "Usuario" ("id_usuario") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Productor" ADD FOREIGN KEY ("id_usuario") REFERENCES "Usuario" ("id_usuario") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "ProfesorJefe" ADD FOREIGN KEY ("id_usuario") REFERENCES "Productor" ("id_usuario") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Estudiante" ADD FOREIGN KEY ("id_curso") REFERENCES "Curso" ("id_curso") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Curso" ADD FOREIGN KEY ("id_pj") REFERENCES "ProfesorJefe" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Caso" ADD FOREIGN KEY ("id_coordinador") REFERENCES "Coordinador" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Hito" ADD FOREIGN KEY ("id_caso") REFERENCES "Caso" ("id_caso") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Incidente" ADD FOREIGN KEY ("id_productor") REFERENCES "Usuario" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE; -- TODO: Esta restricción se puede cambiar por herencia de coordinador a Productor, sería mejor.
ALTER TABLE "Incidente" ADD FOREIGN KEY ("id_caso") REFERENCES "Caso" ("id_caso") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Documento" ADD FOREIGN KEY ("id_hito") REFERENCES "Hito" ("id_hito") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Documento" ADD FOREIGN KEY ("id_incidente") REFERENCES "Incidente" ("id_incidente") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Documento" ADD FOREIGN KEY ("id_caso") REFERENCES "Caso" ("id_caso") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Estudiante_Caso" ADD FOREIGN KEY ("id_estudiante") REFERENCES "Estudiante" ("id_estudiante") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Estudiante_Caso" ADD FOREIGN KEY ("id_caso") REFERENCES "Caso" ("id_caso") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Estudiante_Incidente" ADD FOREIGN KEY ("id_estudiante") REFERENCES "Estudiante" ("id_estudiante") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Estudiante_Incidente" ADD FOREIGN KEY ("id_incidente") REFERENCES "Incidente" ("id_incidente") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Estudiante_Hito" ADD FOREIGN KEY ("id_estudiante") REFERENCES "Estudiante" ("id_estudiante") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Estudiante_Hito" ADD FOREIGN KEY ("id_hito") REFERENCES "Hito" ("id_hito") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
